### ISSUE TITLE
will it work with Nikon in bulb mode?

### ISSUE THREAD

**Issue by zhangh12** [marcocipriani01/shooot#1]
I notice that your library relies on gphoto2, which indicates in its website that "We do not know how to do Bulb capture yet (for Nikon)". I wonder did you find a solution for this in your library? Thank you.

**Comment by marcocipriani01** [comment]
Yes! Unfortunately, documentation on the website is outdated.
Make sure that your DSLR has been released after D7000 (prior to it, bulb mode wasn't available via USB): see [Comparison of Nikon DSLR cameras § References](https://en.wikipedia.org/wiki/Comparison_of_Nikon_DSLR_cameras#References). You can also give a try with an older one.
My `bulb` script uses `gphoto2 --set-config shutterspeed=Bulb --set-config capturetarget=1 --set-config bulb=1 --wait-event=${duration}s --set-config bulb=0 --quiet` and then downloads the latest photo in the SD card. Trigger capture won't work in bulb mode.
Tested with a Nikon D3300.
Kind regards,
marcocipriani01

**Comment by zhangh12** [comment]
> Yes! Unfortunately, documentation on the website is outdated.
> Make sure that your DSLR has been released after D7000 (prior to it, bulb mode wasn't available via USB): see [Comparison of Nikon DSLR cameras § References](https://en.wikipedia.org/wiki/Comparison_of_Nikon_DSLR_cameras#References). You can also give a try with an older one.
> My `bulb` script uses `gphoto2 --set-config shutterspeed=Bulb --set-config capturetarget=1 --set-config bulb=1 --wait-event=${duration}s --set-config bulb=0 --quiet` and then downloads the latest photo in the SD card. Trigger capture won't work in bulb mode.
> Tested with a Nikon D3300.
> Kind regards,
> marcocipriani01

Appreciated it!!!
